// <auto-generated />
using System;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using Resume.Data;

namespace Resume.Migrations.Conspectus
{
    [DbContext(typeof(ConspectusContext))]
    [Migration("20210223220514_SkillstoSkill")]
    partial class SkillstoSkill
    {
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "5.0.2");

            modelBuilder.Entity("Resume.Models.Conspectus", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("TEXT");

                    b.Property<string>("Contact")
                        .HasColumnType("TEXT");

                    b.Property<string>("ContactName")
                        .HasColumnType("TEXT");

                    b.Property<string>("Education")
                        .HasColumnType("TEXT");

                    b.Property<string>("EducationName")
                        .HasColumnType("TEXT");

                    b.Property<string>("Experience")
                        .HasColumnType("TEXT");

                    b.Property<string>("ExperienceName")
                        .HasColumnType("TEXT");

                    b.Property<string>("ResumeName")
                        .HasColumnType("TEXT");

                    b.Property<string>("Skill")
                        .HasColumnType("TEXT");

                    b.Property<string>("SkillName")
                        .HasColumnType("TEXT");

                    b.Property<string>("Summary")
                        .HasColumnType("TEXT");

                    b.Property<string>("SummaryName")
                        .HasColumnType("TEXT");

                    b.Property<Guid>("UId")
                        .HasColumnType("TEXT");

                    b.Property<string>("UserDisplayName")
                        .HasColumnType("TEXT");

                    b.HasKey("Id");

                    b.ToTable("Conspectus");
                });
#pragma warning restore 612, 618
        }
    }
}
